# Generated by Django 3.1.4 on 2021-02-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content_a', models.TextField()),
                ('images_i', models.ImageField(upload_to=None)),
                ('images_comment_i', models.CharField(max_length=100)),
                ('images_review_i', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PresentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content_1', models.TextField()),
                ('content_2', models.TextField()),
                ('images', models.ImageField(upload_to=None)),
            ],
        ),
    ]
