# Generated by Django 3.1.4 on 2021-02-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentpost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryModel_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content_1', models.TextField()),
                ('content_2', models.TextField()),
                ('content_3', models.TextField()),
                ('images_1', models.ImageField(upload_to=None)),
                ('images_comment_1', models.CharField(max_length=100)),
                ('images_review_1', models.IntegerField(blank=True, default=0, null=True)),
                ('images_2', models.ImageField(upload_to=None)),
                ('images_comment_2', models.CharField(max_length=100)),
                ('images_review_2', models.IntegerField(blank=True, default=0, null=True)),
                ('images_3', models.ImageField(upload_to=None)),
                ('images_comment_3', models.CharField(max_length=100)),
                ('images_review_3', models.IntegerField(blank=True, default=0, null=True)),
                ('images_4', models.ImageField(upload_to=None)),
                ('images_comment_4', models.CharField(max_length=100)),
                ('images_review_4', models.IntegerField(blank=True, default=0, null=True)),
                ('images_5', models.ImageField(upload_to=None)),
                ('images_comment_5', models.CharField(max_length=100)),
                ('images_review_5', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
